### ISSUE TITLE
Dead link to sanger virtual machine on main page (https://sanger-pathogens.github.io/iva/)

### ISSUE THREAD

**Issue by eccen** [sanger-pathogens/iva#105]
Under "Introduction" at https://sanger-pathogens.github.io/iva/ there is a link in the sentence: "IVA is installed on the Sanger pathogens virtual machine" that points to http://sanger-pathogens.github.io/pathogens-vm/, which is dead.

**Comment by puethe** [comment]
Thanks. The link has been removed.
