### ISSUE TITLE
support an explicit output argument 

### ISSUE THREAD

**Issue by biorelated** [sanger-pathogens/iva#53]
Support for a ``-o`` or ``--output_dir`` argument for the output folder. Currently attempting to run IVA as part of an automated pipeline and getting an error 

``iva --threads $T --verbose 2 -f $forwards -r $reverse $output_dir ``

``$output_dir`` is a path to the output directory 

I get an error 
``iva: error: unrecognized argurments assembly/samplename``

How can this be resolved?

**Comment by martinghunt** [comment]
The --verbose option doesn't take any values. Use it more times for more verbosity. This works for me:

    iva --threads $T --verbose --verbose -f $forwards -r $reverse $output_dir

or less typing to do:

    iva --threads $T -v -v -f $forwards -r $reverse $output_dir

**Comment by biorelated** [comment]
OK. It was not clear from the documentation that the -v option does not take arguments. Thank you for the clarification!
