### ISSUE TITLE
IVA: error: unrecognized arguments: path_to_output_directory

### ISSUE THREAD

**Issue by biorelated** [sanger-pathogens/iva#56]
I am running into this error while using IVA. 
`IVA: error: unrecognized arguments: path_to_output_directory`

the commandline arguments are
`iva --threads 10 --verbose 2 -f forward_reads.gz  -r reverse_reads.gz output_directory`

**Comment by martinghunt** [comment]
Can you let me know which version of IVA you are running (iva --version)? I can't reproduce this error. Could you also paste the entire terminal output?

Does
iva --test out_dir
work for you?

Thanks,
Martin

**Comment by biorelated** [comment]
I am running IVA version 1.0.3 as part of a SLURM batch script.  This is what I get in my error file. 
```
usage: iva [options] {-f reads_fwd -r reads_rev | --fr reads} <output directory>
iva: error: unrecognized arguments: assemblies/iva/9465_1#13
```
This is how I call it from my batch script. 
```
if [[ $ASSEMBLER == "iva" ]]; then
    module load iva/1.0.3

    echo "de novo assembly with IVA"

    mkdir -p "$OUTPUT_DIR/$ASSEMBLER"

    iva --threads "$THREADS" --verbose 2 -f "$FORWARD" -r "$REVERSE" "$OUTPUT_DIR/$ASSEMBLER/$SAMPLENAME"
```

I ran `iva --test out_dir ` and it works.

my module environment has all the dependencies

```
Currently Loaded Modulefiles:
  1) python/3.5.0                3) MUMmer/3.23                 5) samtools/1.2                7) perl/5.22.0                 9) bioperl/1.6.923
  2) kmc/2.1.1                   4) smalt/0.7.6                 6) trimmomatic/0.33            8) kraken/kraken-0.10.5-beta  10) iva/qc

```

**Comment by martinghunt** [comment]
If you want double verbosity, use -v -v (ie not -v 2). It's interpreting the 2 as the name of the output directory and getting confused. Try this:

    iva --threads 10 -v -v -f forward_reads.gz -r reverse_reads.gz output_directory

Martin

**Comment by biorelated** [comment]
Thank you Martin.
