### ISSUE TITLE
multithreading smalt error 

### ISSUE THREAD

**Issue by lmoncla** [sanger-pathogens/iva#71]
When running IVA on full genome influenza samples and enabling multiple threads, I get the following smalt error: 

smalt.c:807 ERROR: The two FASTA/FASTQ input file have different numbers of reads
[W::sam_read1] parse error at line 812880
[main_samview] truncated file. 

I do not get this error if I run the same sample with a single thread.

**Comment by martinghunt** [comment]
Could you share the input reads with me please so I can try to debug? Thanks.

**Comment by lmoncla** [comment]
Hi,

Here they are! They have already been trimmed with trimmomatic. Thanks so
much.

Best, ​
 fastqs.zip
<https://drive.google.com/file/d/0B0s7NWreQ5QqWUpNcnFxcVB4LVE/view?usp=drive_web>
​
Louise

**Comment by martinghunt** [comment]
Thanks. What version of IVA did you use and what was the command to run it?

**Comment by lmoncla** [comment]
IVA version 1.0.8
Using kmc version 2.1.1
Using kmc_dump version 2.1.1
Using nucmer version 3.1
Using samtools version 1.3.1
Using smalt version 0.7.6

iva -f 6390_S23_L001_R1_001.trimmed.fastq -r
6390_S23_L001_R2_001.trimmed.fastq IVA_output

**Comment by martinghunt** [comment]
I don't yet know why you didn't get the error with a single thread, but the reason for the error is that there needs to be the same number of reads in the two files. And the N^th read in each file should be mate pairs.

```
$ wc -l *
  1989088 6390_S23_L001_R1_001.trimmed.fastq
  1657760 6390_S23_L001_R2_001.trimmed.fastq
```

If you trim with trimmomatic, then you'll need to only keep the paired reads. Throw away everything else, ie when one read of a pair is removed by trimmomatic.

**Comment by lmoncla** [comment]
Thank you, I will try that. I assume that it is not possible to run IVA on
unpaired reads?

**Comment by martinghunt** [comment]
No, sorry but the read pair information is essential to its algorithm.

**Comment by lmoncla** [comment]
I see, I thought so. Thanks for the very quick reply, I really appreciate
it!
